#pragma once
#define LOCALPLAYER_OFFSET 0x3A
#define REALORIGIN_OFFSET 0x3C
#define DORMANCYINFO_OFFSET 0x58
#define ENTITYTYPE_OFFSET 0xBC
#define SCREENROTATION_OFFSET 0xE4
#define MAXHEALTH_OFFSET 0x1C4
#define HEALTH_OFFSET 0x1C8